# Generated by Django 5.0.7 on 2024-08-06 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_post_created_post_updated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
