# Generated by Django 5.0.7 on 2024-08-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_engine_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=50, verbose_name='цвет'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveSmallIntegerField(verbose_name='год выпуска'),
        ),
    ]
