# Generated by Django 5.0.7 on 2024-08-06 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_equipment_car_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='equipment',
            field=models.ForeignKey(blank=True, choices=[('С', 'Стандарт'), ('К', 'Комфорт'), ('Б', 'Базовая'), ('А', 'Аукционная'), ('Л', 'Люкс')], null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.equipment'),
        ),
    ]
