# Generated by Django 5.0.7 on 2024-08-06 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_car_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='equipment',
            field=models.ForeignKey(blank=True, choices=[('С', 'Стандарт'), ('Б', 'Базовая'), ('Л', 'Люкс'), ('К', 'Комфорт'), ('А', 'Аукционная')], max_length=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.equipment'),
        ),
    ]
