# Generated by Django 5.0.7 on 2024-08-06 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_car_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.equipment'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(choices=[('К', 'Комфорт'), ('Б', 'Базовая'), ('Л', 'Люкс'), ('А', 'Аукционная'), ('С', 'Стандарт')], max_length=1),
        ),
    ]
