# Generated by Django 5.0.7 on 2024-08-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_car_equipment_alter_equipment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(choices=[('Б', 'Базовая'), ('С', 'Стандарт'), ('А', 'Аукционная'), ('Л', 'Люкс'), ('К', 'Комфорт')], max_length=1),
        ),
    ]
