# Generated by Django 5.0.7 on 2024-08-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_alter_equipment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='фото машины'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(choices=[('А', 'Аукционная'), ('К', 'Комфорт'), ('С', 'Стандарт'), ('Л', 'Люкс'), ('Б', 'Базовая')], max_length=1),
        ),
    ]
