# Generated by Django 5.0.7 on 2024-08-07 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChooseBerries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ChooseFruits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decorations', models.CharField(max_length=255)),
                ('occasion', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('delivery_time', models.DateTimeField()),
                ('contact_mail', models.EmailField(max_length=254)),
                ('basket_size', models.CharField(choices=[('S', 'SMALL'), ('L', 'LARGE'), ('M', 'MEDIUM')], max_length=1)),
                ('choose_berries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruits.chooseberries')),
                ('choose_fruits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruits.choosefruits')),
            ],
        ),
    ]
