# Generated by Django 5.0.7 on 2024-08-10 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='checkoutcart',
            name='id',
        ),
        migrations.AlterField(
            model_name='checkoutcart',
            name='basket_size',
            field=models.CharField(choices=[('L', 'LARGE'), ('S', 'SMALL'), ('M', 'MEDIUM')], max_length=1, verbose_name='размер корзины'),
        ),
        migrations.AlterField(
            model_name='checkoutcart',
            name='choose_berries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruits.chooseberries', verbose_name='ягоды'),
        ),
        migrations.AlterField(
            model_name='checkoutcart',
            name='choose_fruits',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruits.choosefruits', verbose_name='фрукты'),
        ),
        migrations.AlterField(
            model_name='checkoutcart',
            name='contact_mail',
            field=models.EmailField(max_length=254, unique=True, verbose_name='адрес почты'),
        ),
        migrations.AlterField(
            model_name='checkoutcart',
            name='decorations',
            field=models.CharField(max_length=255, verbose_name='оформление'),
        ),
        migrations.AlterField(
            model_name='checkoutcart',
            name='delivery_time',
            field=models.DateTimeField(verbose_name='время доставки'),
        ),
        migrations.AlterField(
            model_name='checkoutcart',
            name='occasion',
            field=models.CharField(max_length=255, verbose_name='повод'),
        ),
        migrations.AlterField(
            model_name='checkoutcart',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='fruits.address', verbose_name='адрес доставки'),
        ),
    ]
