# Generated by Django 5.0.7 on 2024-08-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0002_address_remove_checkoutcart_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Address'},
        ),
        migrations.AlterModelOptions(
            name='checkoutcart',
            options={'verbose_name_plural': 'Checkout cart'},
        ),
        migrations.AlterModelOptions(
            name='chooseberries',
            options={'verbose_name_plural': 'Choose berries'},
        ),
        migrations.AlterModelOptions(
            name='choosefruits',
            options={'verbose_name_plural': 'Choose fruits'},
        ),
        migrations.AlterField(
            model_name='checkoutcart',
            name='basket_size',
            field=models.CharField(choices=[('M', 'MEDIUM'), ('S', 'SMALL'), ('L', 'LARGE')], max_length=1, verbose_name='размер корзины'),
        ),
        migrations.RemoveField(
            model_name='checkoutcart',
            name='choose_berries',
        ),
        migrations.RemoveField(
            model_name='checkoutcart',
            name='choose_fruits',
        ),
        migrations.AddField(
            model_name='checkoutcart',
            name='choose_berries',
            field=models.ManyToManyField(to='fruits.chooseberries', verbose_name='ягоды'),
        ),
        migrations.AddField(
            model_name='checkoutcart',
            name='choose_fruits',
            field=models.ManyToManyField(to='fruits.choosefruits', verbose_name='фрукты'),
        ),
    ]
